DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    ID    BIGINT PRIMARY KEY AUTO_INCREMENT,
    GENRE VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE       VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT         NOT NULL,
    AUTHOR_ID   BIGINT NOT NULL REFERENCES  AUTHORS (ID),
    GENRE_ID    BIGINT NOT NULL REFERENCES GENRES (ID)
);

DROP TABLE IF EXISTS COMMENTS;
CREATE TABLE COMMENTS
(
    ID      BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BOOK_ID BIGINT NOT NULL REFERENCES BOOKS (ID),
    COMMENT VARCHAR(255) NOT NULL
);