DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES
(
    ID   BIGINT PRIMARY KEY AUTO_INCREMENT,
    GENRE VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS
(
    ID        BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE     VARCHAR(255) NOT NULL,
    DESCRIPTION     TEXT NOT NULL,
    AUTHOR_ID BIGINT REFERENCES AUTHORS(ID),
    GENRE_ID  BIGINT REFERENCES GENRES(ID)
);

-- ALTER TABLE BOOKS ADD FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(ID);
-- ALTER TABLE BOOKS ADD FOREIGN KEY (GENRE_ID) REFERENCES GENRES(ID);

-- DROP TABLE IF EXISTS BOOK_AUTHOR;
-- CREATE TABLE BOOK_AUTHOR
-- (
--     BOOK_ID   BIGINT NOT NULL,
--     AUTHOR_ID BIGINT NOT NULL,
--     FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID),
--     FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (ID),
--     UNIQUE (BOOK_ID, AUTHOR_ID)
-- );
--
-- DROP TABLE IF EXISTS BOOK_GENRE;
-- CREATE TABLE BOOK_GENRE
-- (
--     BOOK_ID  BIGINT NOT NULL,
--     GENRE_ID BIGINT NOT NULL,
--     FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (ID),
--     FOREIGN KEY (GENRE_ID) REFERENCES GENRES (ID),
--     UNIQUE (BOOK_ID, GENRE_ID)
-- );